<a href="https://colab.research.google.com/github/Mradul2k04/Machine_Learning/blob/Linear_Algebra/Basic_Leaner_and__Matrix_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/hdfc_loan_dataset_full_enriched - hdfc_loan_dataset_full_enriched.csv")

In [3]:
df

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,HDFC100996,HDFC Bank,Simran Kaur,Male,Yes,1,Graduate,Salaried,44713,0,...,10.965,Neutral,Sikh,Tamil Nadu,Coimbatore,6635,3.830000e+11,9350952889,simran.kaur@example.in,Medical Representative
996,HDFC100997,HDFC Bank,Krishna Mehta,Male,No,2,Graduate,Salaried,70886,0,...,3.268,Negative,Hindu,Kerala,Trivandrum,217843,7.040000e+11,9176504718,krishna.mehta@example.in,Customer Support Executive
997,HDFC100998,HDFC Bank,Rohan Verma,Female,No,1,Graduate,Salaried,24392,11337,...,0.703,Positive,Hindu,Delhi,New Delhi,89211,9.954289e+10,9966866798,rohan.verma@example.in,Driver
998,HDFC100999,HDFC Bank,Ananya Joshi,Female,No,2,Graduate,Salaried,64803,94136,...,0.377,Negative,Hindu,Gujarat,Ahmedabad,532976,6.170000e+11,9103847156,ananya.joshi@example.in,Electrician
999,HDFC101000,HDFC Bank,Saanvi Reddy,Female,Yes,0,Graduate,Self-Employed,22938,0,...,0.222,Neutral,Hindu,Uttar Pradesh,Noida,509612,6.510000e+11,9449234359,saanvi.reddy@example.in,Marketing Executive

In [4]:
#To check the null values
df.isna().sum()

Loan_ID                          0
Bank                             0
Customer_Name                    0
Gender                           0
Married                          0
Dependents                       0
Education                        0
Employment_Status                0
Applicant_Income                 0
Coapplicant_Income               0
Loan_Amount                      0
Loan_Term_Months                 0
Credit_History                   0
Property_Area                    0
Age                              0
Loan_Status                      0
CIBIL_Score                      0
Annual_Household_Income          0
Debt_to_Income_Ratio             0
Purpose_of_Loan                  0
Existing_EMIs                    0
Number_of_Previous_Loans         0
Default_History_Count            0
Employment_Length_Years          0
Business_Type                  799
Asset_Value                      0
Guarantor                        0
Co-signer_Relationship         234
Monthly_Expense                  0
Organization_Type                0
Region_Branch                    0
Mobile_Verified                  0
Email_Verified                   0
Institutional_Relationships      0
Application_Text                 0
Customer_Feedback                0
Agent_Notes                      0
Loan_to_Annual_Income            0
Customer_Sentiment               0
Religion                         0
State                            0
City                             0
PIN_Code                         0
Aadhaar_Synthetic                0
Phone_Number                     0
Email                            0
Occupation                       0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Loan_ID                      1000 non-null   object
 1   Bank                         1000 non-null   object
 2   Customer_Name                1000 non-null   object
 3   Gender                       1000 non-null   object
 4   Married                      1000 non-null   object
 5   Dependents                   1000 non-null   int64
 6   Education                    1000 non-null   object
 7   Employment_Status            1000 non-null   object
 8   Applicant_Income             1000 non-null   int64
 9   Coapplicant_Income           1000 non-null   int64
 10  Loan_Amount                  1000 non-null   int64
 11  Loan_Term_Months             1000 non-null   int64
 12  Credit_History               1000 non-null   int64
 13  Property_Area                1000 non-null   object
 14  Age                          1000 non-null   int64
 15  Loan_Status                  1000 non-null   object
 16  CIBIL_Score                  1000 non-null   int64
 17  Annual_Household_Income      1000 non-null   int64
 18  Debt_to_Income_Ratio         1000 non-null   float64
 19  Purpose_of_Loan              1000 non-null   object
 20  Existing_EMIs                1000 non-null   int64
 21  Number_of_Previous_Loans     1000 non-null   int64
 22  Default_History_Count        1000 non-null   int64
 23  Employment_Length_Years      1000 non-null   int64
 24  Business_Type                201 non-null    object
 25  Asset_Value                  1000 non-null   int64
 26  Guarantor                    1000 non-null   object
 27  Co-signer_Relationship       766 non-null    object
 28  Monthly_Expense              1000 non-null   int64
 29  Organization_Type            1000 non-null   object
 30  Region_Branch                1000 non-null   object
 31  Mobile_Verified              1000 non-null   object
 32  Email_Verified               1000 non-null   object
 33  Institutional_Relationships  1000 non-null   object
 34  Application_Text             1000 non-null   object
 35  Customer_Feedback            1000 non-null   object
 36  Agent_Notes                  1000 non-null   object
 37  Loan_to_Annual_Income        1000 non-null   float64
 38  Customer_Sentiment           1000 non-null   object
 39  Religion                     1000 non-null   object
 40  State                        1000 non-null   object
 41  City                         1000 non-null   object
 42  PIN_Code                     1000 non-null   int64
 43  Aadhaar_Synthetic            1000 non-null   float64
 44  Phone_Number                 1000 non-null   int64
 45  Email                        1000 non-null   object
 46  Occupation                   1000 non-null   object
dtypes: float64(3), int64(17), object(27)
memory usage: 367.3+ KB

In [6]:
#Finding the Per month income of the Applicant
Montly_household_income=df['Applicant_Income']+df['Coapplicant_Income']
print("Montly income per Applicant+Coapplicant\n" ,Montly_household_income)

Montly income per Applicant+Coapplicant
 0       56976
1        1856
2       64553
3       88450
4        9539
        ...
995     44713
996     70886
997     35729
998    158939
999     22938
Length: 1000, dtype: int64

In [7]:
#Monthly Amount Leaft After all Expense
Monthly_Savings=Montly_household_income-df['Monthly_Expense']
print("Monthly Savings\n" ,Monthly_Savings)

Monthly Savings
 0      26585
1          0
2      39996
3      51700
4       5619
       ...
995    32814
996    38428
997    12752
998    86563
999     6833
Length: 1000, dtype: int64

In [8]:
#SCALAR MULTIPLICATION
#Growth Rate per Month
growth_rate = 1.05
projected_income = df.Applicant_Income * growth_rate
print("Projected Income\n" ,projected_income)

Projected Income
 0      59824.80
1       1948.80
2      67780.65
3      92872.50
4      10015.95
         ...
995    46948.65
996    74430.30
997    25611.60
998    68043.15
999    24084.90
Name: Applicant_Income, Length: 1000, dtype: float64

In [9]:
print(f"\nGrowth amount:\n {(projected_income - df.Applicant_Income)}")

Growth amount:
 0      2848.80
1        92.80
2      3227.65
3      4422.50
4       476.95
        ...
995    2235.65
996    3544.30
997    1219.60
998    3240.15
999    1146.90
Name: Applicant_Income, Length: 1000, dtype: float64

In [10]:
df

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,HDFC100996,HDFC Bank,Simran Kaur,Male,Yes,1,Graduate,Salaried,44713,0,...,10.965,Neutral,Sikh,Tamil Nadu,Coimbatore,6635,3.830000e+11,9350952889,simran.kaur@example.in,Medical Representative
996,HDFC100997,HDFC Bank,Krishna Mehta,Male,No,2,Graduate,Salaried,70886,0,...,3.268,Negative,Hindu,Kerala,Trivandrum,217843,7.040000e+11,9176504718,krishna.mehta@example.in,Customer Support Executive
997,HDFC100998,HDFC Bank,Rohan Verma,Female,No,1,Graduate,Salaried,24392,11337,...,0.703,Positive,Hindu,Delhi,New Delhi,89211,9.954289e+10,9966866798,rohan.verma@example.in,Driver
998,HDFC100999,HDFC Bank,Ananya Joshi,Female,No,2,Graduate,Salaried,64803,94136,...,0.377,Negative,Hindu,Gujarat,Ahmedabad,532976,6.170000e+11,9103847156,ananya.joshi@example.in,Electrician
999,HDFC101000,HDFC Bank,Saanvi Reddy,Female,Yes,0,Graduate,Self-Employed,22938,0,...,0.222,Neutral,Hindu,Uttar Pradesh,Noida,509612,6.510000e+11,9449234359,saanvi.reddy@example.in,Marketing Executive

In [11]:
#Matrix Transpose
matrix = df[[
    'Applicant_Income',
    'Coapplicant_Income',
    'Loan_Amount'
]].values

In [12]:
transposed = matrix.T
print(transposed)

[[  56976    1856   64553 ...   24392   64803   22938]
 [      0       0       0 ...   11337   94136       0]
 [8031545  899361 2387748 ...  301249  719891   61019]]

In [13]:
# Dot Product
features = df[['CIBIL_Score', 'Applicant_Income', 'Employment_Length_Years']].values
weights = np.array([0.5, 0.3, 0.2])

risk_scores = features @ weights
print("Risk Scores\n" ,risk_scores)

Risk Scores
 [17442.5   910.3 19686.6 26874.1  3159.1 12096.4 24715.8   361.5  5599.2
 21691.9  7995.4 11824.5 19341.6  5687.8 16463.2 17187.3  9098.3  3502.2
 11830.5 13367.8 14948.2  4957.4 17234.5 29679.  13913.5 10790.   3148.8
  1143.2 16747.8 13326.5 27274.1  7264.9 28140.1 12097.9 17088.3 10401.1
  8842.9 10476.1  7353.4 39086.9  1243.  18321.5  9437.6 14979.7 18963.6
  8552.8 16195.9 16321.  27757.8 14675.2 28216.1   799.2 24533.3 28632.5
  8602.3  7428.8 10525.5  9785.6 36662.3 12074.  20928.3  8038.3  9354.9
 14078.1 24676.2  9086.  20014.9 20360.4 11256.4 16197.9  4899.   1858.2
 16223.6 16281.2  6771.  11272.4 12394.9 11796.6  3938.7   365.7 21930.
 33979.5  1853.5  1231.5  8767.4  2683.7 27375.8 30922.3  2652.  19133.5
 19146.2  1227.2  6645.4 14051.6 18348.2  2992.2 21192.2 30251.6 25393.5
  1176.9 25166.6 32301.6 10058.5  4492.8 26299.8 22783.1 13494.1 29836.7
  2673.3 18374.9 24117.7 28138.8  1180.4 26591.   1882.  11486.8 23834.7
 45113.6 17762.5 27467.1  1237.5  8614.5  2261.1 21450.1  4219.8 12283.7
 14561.7  2825.8  7851.4 26710.2 19619.2  5925.3  5966.7  4191.8  6859.4
 18588.9  1766.  19251.7 11551.1  8178.   8177.6 11827.9  1182.  25240.2
 10207.1 27431.4 24093.6 13737.  21226.8 24965.5 16688.6  9062.5 14086.9
 24922.7 23600.4 16507.1 16314.5  7908.6  1268.2  7237.  17710.6  3605.1
  5473.7  9809.8  9160.  11701.5  3087.6 11714.9  2077.5 17147.5 13694.6
 14895.3  3063.2  1820.   9858.6 18447.3 27335.9  4303.1 17801.7 10604.6
  8992.2 20595.3 17333.  15679.9  2918.2 22608.8 22895.2  8892.5  5744.
  8360.3  7916.8 20496.7  5063.1 19580.4 12588.2 11881.7 10933.  35937.9
 23614.6 22799.7 14070.8 24937.4  3202.1  8480.4  1240.1 13455.8 16111.5
 13032.4 20160.  26314.7 18856.8 21250.8  7671.2 17316.7 20591.4 18148.8
  6600.4 17200.8 12906.6 17800.5 15074.1 12540.4 11558.3 15601.6 16500.6
 12913.1 16887.4 20875.  21614.9  1222.1 16848.3 19974.4 20869.9 25796.2
 13624.6 33928.  24912.7  5849.4  3646.8  7023.1  9575.   7087.   4478.7
 10098.8  5316.3 14978.6 14185.  16595.9  6204.5 12453.7 23091.3  7843.6
 10885.5  9549.8 10762.2 15414.9 12629.6  1224.5 16104.9  4563.1  5019.3
 18160.2  1297.6 29242.  14682.9  1226.  16578.7 15695.9 14072.3  1846.9
  4087.  11145.2 17788.7   289.7  4878.2  9601.9  2443.  14128.3   362.9
  5924.7 16805.5  7933.3  9541.8 23092.5 25766.   6298.   2300.6  1394.1
 22325.8 29435.8   281.   1801.  11668.2 12720.3 26260.6 16378.9 12973.3
 10854.4  3577.8  3020.   1553.4 13816.   6814.5  9719.9  4029.5  7860.8
 24559.1  1203.2 15566.1 16787.1 18958.4 12875.  11912.6 10899.8 22859.1
 11895.3 23670.2 20795.1  4098.5  7677.7  3738.8  5910.4  2642.3  4450.
  6971.2 15230.8  2707.8 10001.6  7830.9 27425.6 10681.   4773.7 18362.7
  6338.7 21266.7 16839.5 16344.1  4123.1 12074.5 15080.4 24836.6 20830.7
 23561.6 16740.1 11718.7   314.5  6122.1 12393.7 12401.6 14877.1  1239.7
  2040.1 24009.4 17385.1  1229.3  4827.3  9310.3  1205.9  4582.9  1234.5
 14150.5  3832.4 12936.1  1458.6  4206.8  3567.6  6504.7 23973.4 13369.4
 31575.7  6979.1 14165.4 33114.6 40664.4 16535.9 29018.3  8263.9 10665.1
  4055.7  2184.5 16169.4 28617.7  6697.1 29786.  10797.9  5820.6 17326.3
 13871.8 24254.8 18664.  27249.6 35204.2  1246.6 22936.1 17033.7 24348.7
 22979.  28217.   6149.9 18285.3  2711.7 19178.2 15530.  21064.9 17298.2
  2034.6 20379.  10932.3 16680.3 13032.3 15773.8  5407.9  1868.1 10053.
  1208.9   378.3 10027.3  8094.8  5837.  21265.4   944.8 27983.9 12301.4
 14727.5 12584.1  8447.5 21034.  20441.2  4522.2 17102.2 21423.4   344.9
 27266.2 18242.7 19720.3 19422.3 14415.  20985.5 19106.   1901.6 15706.2
 22846.6  5390.9  3828.3 18031.1  1269.   1012.4   981.6  3681.1 16371.
  2987.5  2819.7 17754.4 11992.3 18119.8 13408.4 17306.4  7291.   2719.8
  3601.3  8035.3  7070.4 25861.5 15810.2 21554.4 15408.6   355.3 10811.1
 30587.2 15410.4 23517.2  3599.1 36353.1 14086.7 10755.4 30111.4 16520.1
  1194.7 15395.1   836.  24720.9  3004.3   373.7  5342.5 13013.1  1228.7
 28918.6  9554.7 21284.3 14939.8 15709.   1257.9  7926.2 20205.5 10459.5
  1257.6 24887.2 29159.   3406.5  2752.4 12397.3 14835.1 14977.4  4063.6
  2703.4 18147.6 30208.3 25649.7 14550.  22866.8  4130.9  1838.4 18219.9
 17042.7  6372.9  6998.2 18305.3  6667.6 34828.2 18089.5  1854.6  1876.8
  6112.  13911.5  2942.2 18664.  10448.  15076.5 12898.8  7517.8 19335.1
  6602.7  9903.8  1161.8  9014.3  9171.2 23226.8  1336.2  1856.5 16580.3
 14926.6 12262.3 13254.5 19695.3 21760.6 18974.3  1236.8 12283.3  5105.8
 13629.3 18441.9 21074.9  3471.4 13356.6  3636.5  9480.  19972.7 19027.9
  8011.3 24696.7 11882.1 20997.8  6306.4 22634.2 15503.2 14509.9  1358.
  6206.1  3306.5  9449.8  8010.8 18545.7  1167.  13395.1 13918.4  3192.9
 12698.1 25128.5 16319.1  2486.3  3127.8 12005.3  3720.1 18904.7  5583.9
  5433.4 19929.3 15277.7 30128.9 18549.6  9947.   8611.6 13042.4 15946.2
 22109.3  3170.9  9812.1 10318.3  5725.4 32704.1 24321.4 15781.7  1303.
 25445.4 10321.7  2116.9  8163.4 19698.5 17826.7 16538.8  1857.9  2044.5
  5292.9  6968.  12156.5 15559.7 18649.5  1205.1 14760.4 12571.4  9520.8
 12008.8 18810.4  2904.5  6716.2  6764.4 30676.7  3459.9 11475.5  3020.3
 14920.8 13984.2 13483.6 19764.4 14414.9 12538.8 24159.  16492.6  8830.8
  2889.2  4740.4 17826.4 24312.4 10540.4 10419.9 14359.8 17624.  30848.7
  1227.7  3011.6  9119.9 24139.4 25999.3  7273.5 19966.8 10805.1  1802.7
 20448.2 10797.9 18435.5  4531.4  1253.  18268.1 16633.3  4093.1  8761.
 15093.5 20283.   2260.   8943.3 25139.6 11537.3  4092.9 24400.1  8882.5
 16886.4 25995.5 22812.6 31151.1  1789.7 27485.  30075.   1224.1  1216.7
  7144.4 16341.   3315.3 19233.1 14866.1 16520.9 20873.9 31205.5 15504.
 23575.2 23853.4  2798.3  1223.2  1793.9 16084.5   893.5  1918.7  4837.2
  7974.5 23777.2  9311.8 18437.3  9711.8  4244.7 29470.6 11037.3  5117.5
  3502.   9861.3  1459.1  4872.2 21664.8 15557.2  5658.1 31848.5 13168.8
 14033.4 15476.2  5787.4 23920.3  1257.2   304.  11008.9  1224.2 21812.7
  9374.7 15815.3 17910.7 20724.3 13748.1 23582.6  1200.5 13376.1 20484.1
 14707.2  8720.4 21194.7  8466.5 14717.7 21187.9  2653.7 16856.4 13894.8
 14770.7 12152.   6572.2  7089.5 14543.1  4190.  12152.5 10497.   7051.8
 29525.6 15841.1 19903.  16315.7  8071.1 10886.2 18468.1 18062.1 12665.8
 11674.4 15056.9 18595.4  2172.1  8609.2 12784.6  8378.1 18133.2 11981.
  4364.1  1257.  32267.3 13085.6 21557.9  9578.1 27319.  21606.6 19952.7
 12496.2 25640.1  7333.1 19829.7  7696.4 11855.2 12365.1  1609.4 12961.7
 16955.8  4632.4  1854.7 10242.3 17899.1  5839.5  3385.7 18042.6 20257.5
  3137.2 15479.9  7964.1  7645.1 17216.9  4991.3  8642.5  3794.  14963.1
 17948.7 13757.4 21030.7 10203.6  4158.4 18588.2 14460.7  5265.7  4399.9
  9805.7  1390.6 18939.9 23622.2 22938.1  6965.8 14032.7  2697.3  6900.9
 12162.4  8194.8 21868.5 16245.3 24035.9  9888.2 25084.2  3566.1 15829.5
 12046.1  2023.2  4409.6 20444.6  1955.4 16093.6 12209.  18550.3 17476.6
 21341.6 11904.4 22669.3 14624.9 15846.7  2637.9 17553.  26337.6 13222.9
 18499.5 22520.3 29753.6  5755.8  1353.9 26434.3 23822.3 10325.8  9426.2
 19094.6 20456.4  1467.6 11960.5  6996.9 18235.7   348.7 24135.5 13318.9
  3154.5 15892.7  1312.7 11898.9 13398.6 10358.1 31054.5  8176.6 11181.6
 17201.1 12854.9 32523.6 11693.4 10808.4  1248.9 29548.3 14753.7 25607.7
 10690.4 12937.4  1242.7  4050.4 20926.7 10439.7  2300.5 11157.9 14066.6
  2414.4  5133.8 12012.5 26807.1  1752.9  3153.9 20720.6 21244.8  7897.3
  1989.5  1244.4 14269.   1259.9 10494.6 17262.9  1228.2  8961.1  8659.6
 19807.4  4049.2 26670.2 19167.2 13384.4 17829.5  4962.1  4009.8  9541.1
 11427.2  8627.1 22632.7 10712.6 18198.   1232.5  5061.  24558.8  8619.9
  7972.   8975.1 29169.6  9088.1  2081.6 18813.9 10899.4 17913.  16646.1
  3060.  26333.6  5495.   5867.6 19300.5 16985.5  3827.7 19495.1 17219.9
 11360.5 25419.  20553.5  2718.   3553.1  2734.4  1188.5 25218.9  1754.3
  5022.2 24899.5  6137.3 23010.2 20578.   8033.2 25212.8  2551.4  1228.4
 19588.1 24496.   6088.4  5203.  13067.7 15177.   6483.4 20263.5 13078.9
  8615.9 17576.6 15006.3  3821.  37717.5 19832.7 12960.1 10215.5 16492.7
  4540.5 17875.4 12362.4 12981.  17796.  13767.8 21546.5  7680.1 19781.2
  7226.4]

In [14]:
#Covariance & Correlation Matrix
fin_cols = ['Applicant_Income', 'Loan_Amount', 'CIBIL_Score', 'Debt_to_Income_Ratio', 'Asset_Value']
cov_matrix = np.cov(df[fin_cols].values.T)
print("Covariance Matrix\n" ,cov_matrix)

Covariance Matrix
 [[ 7.91477548e+08  7.53314000e+08  6.38023346e+04 -6.27524305e+06
   3.40826506e+10]
 [ 7.53314000e+08  6.94333531e+12  3.16092409e+06  5.87761780e+07
   9.82151967e+10]
 [ 6.38023346e+04  3.16092409e+06  5.45183467e+03  3.44266997e+03
   4.02042623e+06]
 [-6.27524305e+06  5.87761780e+07  3.44266997e+03  3.89904162e+06
  -2.63208192e+08]
 [ 3.40826506e+10  9.82151967e+10  4.02042623e+06 -2.63208192e+08
   2.19469831e+12]]

In [15]:
corr_matrix = np.corrcoef(df[fin_cols].values.T)
print("Correlation Matrix\n" ,corr_matrix)

Correlation Matrix
 [[ 1.          0.01016185  0.03071468 -0.11296199  0.81776148]
 [ 0.01016185  1.          0.01624646  0.01129636  0.0251598 ]
 [ 0.03071468  0.01624646  1.          0.02361267  0.03675474]
 [-0.11296199  0.01129636  0.02361267  1.         -0.08997732]
 [ 0.81776148  0.0251598   0.03675474 -0.08997732  1.        ]]

In [16]:
#Scaler Vector Multtiplication
#Rising the Applicant Inome by 7%
df['Applicant_Income'] = df['Applicant_Income'] * 1.07
print(df['Applicant_Income'])

0      60964.32
1       1985.92
2      69071.71
3      94641.50
4      10206.73
         ...
995    47842.91
996    75848.02
997    26099.44
998    69339.21
999    24543.66
Name: Applicant_Income, Length: 1000, dtype: float64

In [17]:
#Rate of Interset By Bank
#Rate of intrest increase by bank 5%
df['Rate_of_Interest'] = df['Loan_Amount'] * 0.05
print(df['Rate_of_Interest'])

0      401577.25
1       44968.05
2      119387.40
3       32942.80
4        9933.55
         ...
995    294180.15
996    139011.40
997     15062.45
998     35994.55
999      3050.95
Name: Rate_of_Interest, Length: 1000, dtype: float64